#!/usr/bin/env bash
# MIT License
#
# Copyright (c) 2018 Lazarus Lazaridis
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

function _goto_install_error()
{
	echo "$@" >&2
}

#windows check
ON_WINDOWS=false
if [[ "$OSTYPE" == "msys" ]]; then
	ON_WINDOWS=true
fi

# sudo-check
if [ $EUID -ne 0 ] && [ "$ON_WINDOWS" == false ]; then
	_goto_install_error 'Please run this script in sudo mode or as root user'
	exit
fi

HOME=$(eval echo "~${SUDO_USER}")
if [[ $ON_WINDOWS = true ]]; then
	GOTO_FILE_LOCATION='/usr/bin/goto.sh'
else
	GOTO_FILE_LOCATION='/usr/local/share/goto.sh'
fi

RC=""
if [ -f ~/.bashrc ]; then
	RC="$HOME/.bashrc"
elif [ -f ~/.zshrc ]; then
	RC="$HOME/.zshrc"
fi

cp ./goto.sh "$GOTO_FILE_LOCATION"

if [ -n "$RC" ]; then
	# Append source to RC startup file if not already there
	if [ "$(grep -c "source $GOTO_FILE_LOCATION" "$RC")" == "0" ]; then
		# Append source to RC file
		echo -e "\\n\\n# Source goto\\n[[ -s \"$GOTO_FILE_LOCATION\" ]] && source $GOTO_FILE_LOCATION\\n" >> "$RC"
	fi

	# shellcheck source=/dev/null
	source "$GOTO_FILE_LOCATION"
else
	_goto_install_error "Error sourcing goto in your startup file.."
	_goto_install_error "E.g ~/.bashrc ~/.zshrc etc.."
fi
